In [3]:
import numpy as np
print ("!SELAMAT DATANG DI KALKULATOR SEDERHANA MATRIKS!")
print ("================================================")
K_06 = int(input("Masukkan Jumlah Baris Matriks 1 yang kalian mau: "))
A_06 = int(input("Masukkan Jumlah Kolom Matriks 1 yang kalian mau: "))
print("Masukkan Nilai-nilai Matriks 1: ")
entries= list(map(int, input().split()))
matriks1= np.array(entries).reshape(int(K_06),int(A_06))
print("Matriks 1: ")
print(matriks1)

K_06 = int(input("Masukkan Jumlah Baris Matriks 2 yang kalian mau: "))
A_06 = int(input("Masukkan Jumlah Kolom Matriks 2 yang kalian mau: "))
print("Masukkan Nilai-nilai Matriks 2: ")
entries= list(map(int, input().split()))
matriks2= np.array(entries).reshape(int(K_06),int(A_06))
print("Matriks 2: ")
print(matriks2)

print ("\nSilahkan Pilih Perhitungan Matriks Sesuai Angka:\n 1.Penjumlahan Matriks\n 2.Pengurangan Matriks\n 3.Perkalian Matriks")
Pilihan = int(input("Masukkan Pilihan Anda: "))

if Pilihan == 1:
  print("\nHasil Penjumlahan Matriks kalian adalah: ")
  print(matriks1 + matriks2)

elif Pilihan == 2:
  print("\nHasil Pengurangan Matriks kalian adalah: ")
  print(matriks1 - matriks2)

elif Pilihan == 3:
  Perkalian_Matriks06 = np.dot(matriks1, matriks2)
  print("\nHasil Perkalian 2 Matriks kalian adalah: ")
  print(Perkalian_Matriks06)
print ("TERIMA KASIH SUDAH MENGGUNAKAN AKU YAA:))))")

!SELAMAT DATANG DI KALKULATOR SEDERHANA MATRIKS!


Masukkan Jumlah Baris Matriks 1 yang kalian mau:  3
Masukkan Jumlah Kolom Matriks 1 yang kalian mau:  3


Masukkan Nilai-nilai Matriks 1: 


 2 3 4 5 6 7 8 9 0


Matriks 1: 
[[2 3 4]
 [5 6 7]
 [8 9 0]]


Masukkan Jumlah Baris Matriks 2 yang kalian mau:  3
Masukkan Jumlah Kolom Matriks 2 yang kalian mau:  3


Masukkan Nilai-nilai Matriks 2: 


 0 9 8 7 6 5 4 3 2


Matriks 2: 
[[0 9 8]
 [7 6 5]
 [4 3 2]]

Silahkan Pilih Perhitungan Matriks Sesuai Angka:
 1.Penjumlahan Matriks
 2.Pengurangan Matriks
 3.Perkalian Matriks


Masukkan Pilihan Anda:  3



Hasil Perkalian 2 Matriks kalian adalah: 
[[ 37  48  39]
 [ 70 102  84]
 [ 63 126 109]]
TERIMA KASIH SUDAH MENGGUNAKAN AKU YAA:))))


In [11]:
### import numpy as np
print ("!SELAMAT DATANG DI KALKULATOR SEDERHANA MATRIKS!")
print ("================================================")
K_06 = int(input("Masukkan Jumlah Baris Matriks 1 yang kalian mau: "))
A_06 = int(input("Masukkan Jumlah Kolom Matriks 1 yang kalian mau: "))
print("Masukkan Nilai-nilai Matriks 1: ")
entries= list(map(int, input().split()))
matriks1= np.array(entries).reshape(int(K_06),int(A_06))
print("Matriks 1: ")
print(matriks1)

K_06 = int(input("Masukkan Jumlah Baris Matriks 2 yang kalian mau: "))
A_06 = int(input("Masukkan Jumlah Kolom Matriks 2 yang kalian mau: "))
print("Masukkan Nilai-nilai Matriks 2: ")
entries= list(map(int, input().split()))
matriks2= np.array(entries).reshape(int(K_06),int(A_06))
print("Matriks 2: ")
print(matriks2)

print ("\nSilahkan Pilih Perhitungan Matriks Sesuai Angka:\n 1.Penjumlahan Matriks\n 2.Pengurangan Matriks\n 3.Perkalian Matriks")
Pilihan = int(input("Masukkan Pilihan Anda: "))

if Pilihan == 1:
  print("\nHasil Penjumlahan Matriks kalian adalah: ")
  print(matriks1 + matriks2)

elif Pilihan == 2:
  print("\nHasil Pengurangan Matriks kalian adalah: ")
  print(matriks1 - matriks2)
print ("TERIMA KASIH SUDAH MENGGUNAKAN AKU YAA:))))")

!SELAMAT DATANG DI KALKULATOR SEDERHANA MATRIKS!


Masukkan Jumlah Baris Matriks 1 yang kalian mau:  3
Masukkan Jumlah Kolom Matriks 1 yang kalian mau:  3


Masukkan Nilai-nilai Matriks 1: 


 2 3 0 4 5 6 7 8 9


Matriks 1: 
[[2 3 0]
 [4 5 6]
 [7 8 9]]


Masukkan Jumlah Baris Matriks 2 yang kalian mau:  3
Masukkan Jumlah Kolom Matriks 2 yang kalian mau:  3


Masukkan Nilai-nilai Matriks 2: 


 7 8 9 4 5 6 2 3 0


Matriks 2: 
[[7 8 9]
 [4 5 6]
 [2 3 0]]

Silahkan Pilih Perhitungan Matriks Sesuai Angka:
 1.Penjumlahan Matriks
 2.Pengurangan Matriks
 3.Perkalian Matriks


Masukkan Pilihan Anda:  1



Hasil Penjumlahan Matriks kalian adalah: 
[[ 9 11  9]
 [ 8 10 12]
 [ 9 11  9]]
TERIMA KASIH SUDAH MENGGUNAKAN AKU YAA:))))


In [12]:
### import numpy as np
print ("!SELAMAT DATANG DI KALKULATOR SEDERHANA MATRIKS!")
print ("================================================")
K_06 = int(input("Masukkan Jumlah Baris Matriks 1 yang kalian mau: "))
A_06 = int(input("Masukkan Jumlah Kolom Matriks 1 yang kalian mau: "))
print("Masukkan Nilai-nilai Matriks 1: ")
entries= list(map(int, input().split()))
matriks1= np.array(entries).reshape(int(K_06),int(A_06))
print("Matriks 1: ")
print(matriks1)

K_06 = int(input("Masukkan Jumlah Baris Matriks 2 yang kalian mau: "))
A_06 = int(input("Masukkan Jumlah Kolom Matriks 2 yang kalian mau: "))
print("Masukkan Nilai-nilai Matriks 2: ")
entries= list(map(int, input().split()))
matriks2= np.array(entries).reshape(int(K_06),int(A_06))
print("Matriks 2: ")
print(matriks2)

print ("\nSilahkan Pilih Perhitungan Matriks Sesuai Angka:\n 1.Penjumlahan Matriks\n 2.Pengurangan Matriks\n 3.Perkalian Matriks")
Pilihan = int(input("Masukkan Pilihan Anda: "))

if Pilihan == 1:
  print("\nHasil Penjumlahan Matriks kalian adalah: ")
  print(matriks1 + matriks2)

elif Pilihan == 2:
  print("\nHasil Pengurangan Matriks kalian adalah: ")
  print(matriks1 - matriks2)
print ("TERIMA KASIH SUDAH MENGGUNAKAN AKU YAA:))))")

!SELAMAT DATANG DI KALKULATOR SEDERHANA MATRIKS!


Masukkan Jumlah Baris Matriks 1 yang kalian mau:  3
Masukkan Jumlah Kolom Matriks 1 yang kalian mau:  3


Masukkan Nilai-nilai Matriks 1: 


 2 3 0 4 5 6 7 8 9


Matriks 1: 
[[2 3 0]
 [4 5 6]
 [7 8 9]]


Masukkan Jumlah Baris Matriks 2 yang kalian mau:  3
Masukkan Jumlah Kolom Matriks 2 yang kalian mau:  3


Masukkan Nilai-nilai Matriks 2: 


 7 8 9 4 5 6 2 3 0


Matriks 2: 
[[7 8 9]
 [4 5 6]
 [2 3 0]]

Silahkan Pilih Perhitungan Matriks Sesuai Angka:
 1.Penjumlahan Matriks
 2.Pengurangan Matriks
 3.Perkalian Matriks


Masukkan Pilihan Anda:  2



Hasil Pengurangan Matriks kalian adalah: 
[[-5 -5 -9]
 [ 0  0  0]
 [ 5  5  9]]
TERIMA KASIH SUDAH MENGGUNAKAN AKU YAA:))))
